// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BigImg: typeof import('./../src/components/swiper/BigImg.vue')['default']
    CreditItem: typeof import('./../src/components/swiper/CreditItem.vue')['default']
    DailyItem: typeof import('./../src/components/swiper/DailyItem.vue')['default']
    Empty: typeof import('./../src/components/layout/Empty/index.vue')['default']
    Footer: typeof import('./../src/components/layout/Footer/index.vue')['default']
    HeadSliderItem: typeof import('./../src/components/swiper/HeadSliderItem.vue')['default']
    ListItemBig: typeof import('./../src/components/layout/News/ListItemBig.vue')['default']
    ListItemSmall: typeof import('./../src/components/layout/News/ListItemSmall.vue')['default']
    Loading: typeof import('./../src/components/Loading.vue')['default']
    Navbar: typeof import('./../src/components/layout/Navbar/index.vue')['default']
    PostItem: typeof import('./../src/components/swiper/PostItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmallImg: typeof import('./../src/components/layout/News/SmallImg.vue')['default']
    SmallImgDing: typeof import('./../src/components/layout/News/SmallImgDing.vue')['default']
    SubTitile: typeof import('./../src/components/layout/Title/SubTitile.vue')['default']
    ThemeChange: typeof import('./../src/components/layout/Navbar/components/ThemeChange.vue')['default']
    Toast: typeof import('./../src/components/Toast/Toast.vue')['default']
    Watcher: typeof import('./../src/components/watcher/Watcher.vue')['default']
  }
}
